### ISSUE TITLE
Data inconsistencies

### ISSUE THREAD

**Issue by vegaskev** [blacksonic/angular2-es6-starter#10]
In the demo app, if you add a new post, then go to edit another post, you will always see the same data regardless of the post you are trying to edit.

For example if I click 'Angular', edit post, I will still see the data from a different post, not the 'Angular' post.

Hoping this was just in issue with the current demo, I went ahead and installed on my local machine from the command line, and when I loaded the app locally I experienced similar issues.  For example, I added a post called 'Test post'.  When I saved it and viewed the screen, I saw my new post.  I then went to edit the 'ReactJS' post.  I change the title to 'ReactJSEdited' and selected 'save.  The app took me back to the post archive screen, but instead of editing the 'ReactJS' post with my new title, the 'ReactJS' post stayed the same, but my newly added 'Test Post' was now changed to 'ReactJSEdit' and had all of the data related to the original 'ReactJS' post.

Unfortunately, I'm still pretty noob with MEAN, so I'm not ready to debug this on my own.  But if there's anything I can do to help, please let me know and I'll hack away.

**Comment by blacksonic** [comment]
Managed to reproduce and the bug came from where i searched for the post by id...used ```=``` instead of ```==```.
Fixed it in https://github.com/blacksonic/angular2-es6-starter/commit/c2e6fb713e8daa7155de01803b15b4c7913dbcbd

**Comment by blacksonic** [comment]
Will release it to the online version, thanks for finding it.

**Comment by blacksonic** [comment]
Released, now it should work as expected.
