### ISSUE TITLE
heroku boot.js not found issue 

### ISSUE THREAD

**Issue by itranga** [blacksonic/angular2-es6-starter#8]
I try to deploy code in heroku . I got the following issue in my chrome console 

boot.js  not found 

https://mytemple.herokuapp.com/

i got the same issue in my development pc

**Comment by blacksonic** [comment]
I couldn't reproduce it. What are the steps you made and in what environment? Do you see any error in the console?
```
npm install
gulp serve
```
and ```boot.js``` is present. Also the same for ```gulp dist```.
