### ISSUE TITLE
Gulp Serve Seems To Require Dev Dependencies

### ISSUE THREAD

**Issue by haydenJogs92** [blacksonic/angular2-es6-starter#9]
Hi - I'm new at this - but I couldn't get the app to work with the quick start instructions.

When I follow the instructions:
git clone https://github.com/blacksonic/angular2-es6-starter.git
cd angular2-es6-starter
npm install

gulp serve

The gulp serve command starts asking for modules in the dev dependencies in package.json
For ex:
Error: Cannot find module 'run-sequence'

Should I install dev dependencies as well? After I do npm install, the dev dependencies modules aren't in my node_modules folder.

Thanks for your help.

**Comment by blacksonic** [comment]
Dev dependencies are required for running the application with ```gulp serve```.
Which node version are you using?

**Comment by blacksonic** [comment]
Can you delete ``node_modules``` do a clean install and paste the stack trace also?
It is weird that there is no ```run-sequence```, because tests are passing on Travis.

**Comment by haydenJogs92** [comment]
Thanks for the quick response - I'm running node

v4.3.1

I'm not positive what a stack trace is: but here's the specific error I get.

Haydens-MBP:angular2-es6-starter haydenbrown$ gulp serve

module.js:327

    throw err;

    ^


Error: Cannot find module 'run-sequence'

    at Function.Module._resolveFilename (module.js:325:15)

    at Function.Module._load (module.js:276:25)

    at Module.require (module.js:353:17)

    at require (internal/module.js:12:17)

    at Object.<anonymous>
(/Users/haydenbrown/Desktop/angular2-es6-starter/gulpfile.js:3:19)

    at Module._compile (module.js:409:26)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)

**Comment by haydenJogs92** [comment]
I can of course just add all of the devDepencies contents to dependencies
in package.json

but I thought that npm install would grab all necessary modules.

**Comment by haydenJogs92** [comment]
Yup, copying all modules over to dependencies seems to do the trick. Maybe something is off with my npm, but I'm running version 2.14.12

**Comment by blacksonic** [comment]
On my local machine deleted node_modules and did a full reinstall and everything is working fine.
Npm install skips devDependencies on other repositories also?

**Comment by haydenJogs92** [comment]
Thanks for looking into it.

I believe this is the first time I've run into this problem with npm. On other repos I've used, npm gets devDepencies modules, but not in this case.

**Comment by blacksonic** [comment]
Then I'll close this ticket for now.
